main_networks = [
    "Apple Search Ads",
    "Facebook Ads",
    "googleadwords_int",
    "snapchat_int",
    "tiktokglobal_int",
    "tatari_linear",
    "tatari_streaming",
    "tatari_programmatic",
]
platforms = ["android", "ios"]

alternative_networks = """
Social_twitter
Youtube
blog2blog
applestore
web_checkout
YouTube
appstore
ig
Social_instagram
Tatari_QR-code
Facebook_Web
sleepfoundation
Social_facebook
Social_youtube
social
Facebook
rm_web
youtube
bytedanceglobal_int
web
liftoff_int
Social_tiktok
thesleepdoctor
fbk_ads
Iterable
App Landing Page on Web
wordline_int
Blog-to-app
edge226
sleepdoctor
web'
social_IG_BTS
prodege_int
edge_int
disciplinedigital_int
Tatari
davidstea
affilirev_int
diyomisoftmalta_int
fb
GossipMedia
social_instagram
vibe_int
invalid_media_source_name
3Dweb
quora_int
Closer Look Subscribers 2018
linkin.bio
crm
support
Facebook Ads
Organic
moloco_int
snapchat_int
bytedanceglobal_int
Youtube
ig
GossipMedia
sleepfoundation
Social_twitter
web'
an
convertkit
linkin.bio
email
PNfxQEn_tgU
Tatari
web
Tatari_QR-code
applovin_int
davidstea
influencer_deep_link_test
prodege_int
sleepdoctor
tapjoy_int
Social_facebook
thesleepdoctor
Social_tiktok
Iterable
Email
diyomisoftmalta_int
Social_instagram
Blog-to-app
Facebook_Web
youtube
influencer_dev_test
Social_youtube
YouTube
rm_web
fb
social_instagram
blog2blog
invalid_media_source_name
social
[NEWSLETTER]
vibe_int
liftoff_int
google
web_checkout
lenetworket_int
adssynerg8s_int
mpnd_int
thepurpleline_int
cherishads_int
climateads_int
phnxteam_int
monitie_int
unityads_int
sojoy_int
hotspotmeta_int
singaporexu_int
ihipbrort_int
adsnack_int
Oliveradss_int
z2adigital_int
purifydigital_int
plainad_int
apjoy_int
adstraction_int
mediake_int
aptlinkar_int
twunion_int
dolomitemu4_int
longmiad_int
apptastic_int
tarsan_int
adsplus_int
mintegral_int
particlemedia_int
frostclubads_int
htr_int
humitemobko_int
gridtechmilh_int
breezetechads_int
applovin_int
gowithmedia_int
imalimedia_int
singapore47_int
vungle_int
aplhamedi7k_int
orbitadstech_int
diviadz_int
learnshapwm_int
bfkj_int
gozoy_int
proformics_int
hongkongm5hj_int
digitalrona_int
acesmobie3_int
eternitymobi_int
goapplibai_int
chongdaads_int
particlemedia_int
unityads_int
tarsan_int
growthpowx6_int
ironsource_int
apptrust_int
hitapps_int
mobiaviator_int
vestaapps_int
andrewsmig2_int
bondayadm_int
AT_kevel_int
AT_pulsepoint_int
AT_admob_int
nftdroper_int
targetingexpert_int
AT_bidscube_int
oliveradss_int
Jinglerads_int
apexads_int
apikadss_int
wickerads_int
boongads_int
rogeradss_int
koodadas_int
kiverrads_int
roverads_int
sokomy_int
vidmob_int
keybali_int
cygosport_int
cygobet_int
cygotech_int
wiserollэто
waledigzt_int
imxbiddin2k_int
jujubemob_int
mobptimal_int
blazelabid7_int
mediaxpedia_int
bitsflowfz_int
awstreamifhh_int
cmnetlw_int
bayernaad_int
clnkkiads_int
dhaandads_int
kilemrads_int
killssed_int
koodaads_int
mercakds_int
bayernad_int
commanderad_int
killerads_int
kilsed_int
koodads_int
nyoliads_int
parasad_int
audiaads_int
chanaddas_int
comanderad_int
commmodses_int
hommerads_int
joklerads_int
nyolliads_int
sticerad_int
vittads_int
blinkitsad_int
clnkiads_int
jokerads_int
likkinkad_int
stickerad_int
vitads_int
mercads_int
blinkitssad_int
dooloads_int
likinkad_int
parpasad_int
audiiads_int
chanadas_int
commmodes_int
dhandads_int
doloads_int
homerads_int
"""

alternative_networks = alternative_networks.split("\n")
missing_networks = list(set(alternative_networks) - set(main_networks))
missing_networks.sort()

for network in missing_networks:
    if not network:
        continue
    for platform in platforms:
        print(
            f"""("{platform}", "{network}", "Geobydate", "2000-01-01", "2999-12-31", current_timestamp()),"""
        )
