create or replace table `relax-melodies-android.mappings.country_maps` (
    country_code STRING,
    country_name STRING,
    continent STRING,
    subcontinent STRING,
);


insert into `relax-melodies-android.mappings.country_maps`
values
  ('AF', 'Afghanistan', 'Asia', 'Southern Asia'),
  ('AL', 'Albania', 'Europe', 'Southern Europe'),
  ('DZ', 'Algeria', 'Africa', 'Northern Africa'),
  ('AS', 'American Samoa', 'Oceania', 'Polynesia'),
  ('AD', 'Andorra', 'Europe', 'Southern Europe'),
  ('AO', 'Angola', 'Africa', 'Sub-Saharan Africa'),
  ('AI', 'Anguilla', 'Americas', 'Caribbean'),
  ('AQ', 'Antarctica', 'Antarctica', 'Antarctica'),
  ('AG', 'Antigua and Barbuda', 'Americas', 'Caribbean'),
  ('AR', 'Argentina', 'Americas', 'South America'),
  ('AM', 'Armenia', 'Asia', 'Western Asia'),
  ('AW', 'Aruba', 'Americas', 'Caribbean'),
  ('AU', 'Australia', 'Oceania', 'Australia and New Zealand'),
  ('AT', 'Austria', 'Europe', 'Western Europe'),
  ('AZ', 'Azerbaijan', 'Asia', 'Western Asia'),
  ('BS', 'Bahamas', 'Americas', 'Caribbean'),
  ('BH', 'Bahrain', 'Asia', 'Western Asia'),
  ('BD', 'Bangladesh', 'Asia', 'Southern Asia'),
  ('BB', 'Barbados', 'Americas', 'Caribbean'),
  ('BY', 'Belarus', 'Europe', 'Eastern Europe'),
  ('BE', 'Belgium', 'Europe', 'Western Europe'),
  ('BZ', 'Belize', 'Americas', 'Central America'),
  ('BJ', 'Benin', 'Africa', 'Sub-Saharan Africa'),
  ('BM', 'Bermuda', 'Americas', 'Northern America'),
  ('BT', 'Bhutan', 'Asia', 'Southern Asia'),
  ('BO', 'Bolivia', 'Americas', 'South America'),
  ('BA', 'Bosnia and Herzegovina', 'Europe', 'Southern Europe'),
  ('BW', 'Botswana', 'Africa', 'Sub-Saharan Africa'),
  ('BR', 'Brazil', 'Americas', 'South America'),
  ('IO', 'British Indian Ocean Territory', 'Africa', 'Eastern Africa'),
  ('BN', 'Brunei', 'Asia', 'South-Eastern Asia'),
  ('BG', 'Bulgaria', 'Europe', 'Eastern Europe'),
  ('BF', 'Burkina Faso', 'Africa', 'Sub-Saharan Africa'),
  ('BI', 'Burundi', 'Africa', 'Sub-Saharan Africa'),
  ('KH', 'Cambodia', 'Asia', 'South-Eastern Asia'),
  ('CM', 'Cameroon', 'Africa', 'Sub-Saharan Africa'),
  ('CA', 'Canada', 'Americas', 'Northern America'),
  ('CV', 'Cape Verde', 'Africa', 'Sub-Saharan Africa'),
  ('KY', 'Cayman Islands', 'Americas', 'Caribbean'),
  ('CF', 'Central African Republic', 'Africa', 'Sub-Saharan Africa'),
  ('TD', 'Chad', 'Africa', 'Sub-Saharan Africa'),
  ('CL', 'Chile', 'Americas', 'South America'),
  ('CN', 'China', 'Asia', 'Eastern Asia'),
  ('CX', 'Christmas Island', 'Oceania', 'Australia and New Zealand'),
  ('CC', 'Cocos (Keeling) Islands', 'Oceania', 'Australia and New Zealand'),
  ('CO', 'Colombia', 'Americas', 'South America'),
  ('KM', 'Comoros', 'Africa', 'Sub-Saharan Africa'),
  ('CG', 'Congo (Brazzaville)', 'Africa', 'Sub-Saharan Africa'),
  ('CD', 'Congo (Kinshasa)', 'Africa', 'Sub-Saharan Africa'),
  ('CK', 'Cook Islands', 'Oceania', 'Polynesia'),
  ('CR', 'Costa Rica', 'Americas', 'Central America'),
  ('CI', 'Côte d’Ivoire', 'Africa', 'Sub-Saharan Africa'),
  ('HR', 'Croatia', 'Europe', 'Southern Europe'),
  ('CU', 'Cuba', 'Americas', 'Caribbean'),
  ('CY', 'Cyprus', 'Asia', 'Western Asia'),
  ('CZ', 'Czech Republic', 'Europe', 'Eastern Europe'),
  ('CZ', 'Czechia', 'Europe', 'Eastern Europe'),
  ('DK', 'Denmark', 'Europe', 'Northern Europe'),
  ('DJ', 'Djibouti', 'Africa', 'Eastern Africa'),
  ('DM', 'Dominica', 'Americas', 'Caribbean'),
  ('DO', 'Dominican Republic', 'Americas', 'Caribbean'),
  ('EC', 'Ecuador', 'Americas', 'South America'),
  ('EG', 'Egypt', 'Africa', 'Northern Africa'),
  ('SV', 'El Salvador', 'Americas', 'Central America'),
  ('GQ', 'Equatorial Guinea', 'Africa', 'Sub-Saharan Africa'),
  ('ER', 'Eritrea', 'Africa', 'Sub-Saharan Africa'),
  ('EE', 'Estonia', 'Europe', 'Northern Europe'),
  ('SZ', 'Eswatini', 'Africa', 'Sub-Saharan Africa'),
  ('ET', 'Ethiopia', 'Africa', 'Sub-Saharan Africa'),
  ('FJ', 'Fiji', 'Oceania', 'Melanesia'),
  ('FI', 'Finland', 'Europe', 'Northern Europe'),
  ('FR', 'France', 'Europe', 'Western Europe'),
  ('GA', 'Gabon', 'Africa', 'Sub-Saharan Africa'),
  ('GM', 'Gambia', 'Africa', 'Sub-Saharan Africa'),
  ('GE', 'Georgia', 'Asia', 'Western Asia'),
  ('DE', 'Germany', 'Europe', 'Western Europe'),
  ('GH', 'Ghana', 'Africa', 'Sub-Saharan Africa'),
  ('GR', 'Greece', 'Europe', 'Southern Europe'),
  ('GL', 'Greenland', 'Americas', 'Northern America'),
  ('GD', 'Grenada', 'Americas', 'Caribbean'),
  ('GU', 'Guam', 'Oceania', 'Micronesia'),
  ('GT', 'Guatemala', 'Americas', 'Central America'),
  ('GN', 'Guinea', 'Africa', 'Sub-Saharan Africa'),
  ('GW', 'Guinea-Bissau', 'Africa', 'Sub-Saharan Africa'),
  ('GY', 'Guyana', 'Americas', 'South America'),
  ('HT', 'Haiti', 'Americas', 'Caribbean'),
  ('HN', 'Honduras', 'Americas', 'Central America'),
  ('HK', 'Hong Kong', 'Asia', 'Eastern Asia'),
  ('HU', 'Hungary', 'Europe', 'Eastern Europe'),
  ('IS', 'Iceland', 'Europe', 'Northern Europe'),
  ('IN', 'India', 'Asia', 'Southern Asia'),
  ('ID', 'Indonesia', 'Asia', 'South-Eastern Asia'),
  ('IR', 'Iran', 'Asia', 'Southern Asia'),
  ('IQ', 'Iraq', 'Asia', 'Western Asia'),
  ('IE', 'Ireland', 'Europe', 'Northern Europe'),
  ('IL', 'Israel', 'Asia', 'Western Asia'),
  ('IT', 'Italy', 'Europe', 'Southern Europe'),
  ('JM', 'Jamaica', 'Americas', 'Caribbean'),
  ('JP', 'Japan', 'Asia', 'Eastern Asia'),
  ('JO', 'Jordan', 'Asia', 'Western Asia'),
  ('KZ', 'Kazakhstan', 'Asia', 'Central Asia'),
  ('KE', 'Kenya', 'Africa', 'Sub-Saharan Africa'),
  ('KI', 'Kiribati', 'Oceania', 'Micronesia'),
  ('KR', 'Korea, South', 'Asia', 'Eastern Asia'),
  ('KR', 'South Korea', 'Asia', 'Eastern Asia'),
  ('KW', 'Kuwait', 'Asia', 'Western Asia'),
  ('KG', 'Kyrgyzstan', 'Asia', 'Central Asia'),
  ('LA', 'Laos', 'Asia', 'South-Eastern Asia'),
  ('LV', 'Latvia', 'Europe', 'Northern Europe'),
  ('LB', 'Lebanon', 'Asia', 'Western Asia'),
  ('LS', 'Lesotho', 'Africa', 'Sub-Saharan Africa'),
  ('LR', 'Liberia', 'Africa', 'Sub-Saharan Africa'),
  ('LY', 'Libya', 'Africa', 'Northern Africa'),
  ('LI', 'Liechtenstein', 'Europe', 'Western Europe'),
  ('LT', 'Lithuania', 'Europe', 'Northern Europe'),
  ('LU', 'Luxembourg', 'Europe', 'Western Europe'),
  ('MO', 'Macau', 'Asia', 'Eastern Asia'),
  ('MG', 'Madagascar', 'Africa', 'Sub-Saharan Africa'),
  ('MW', 'Malawi', 'Africa', 'Sub-Saharan Africa'),
  ('MY', 'Malaysia', 'Asia', 'South-Eastern Asia'),
  ('MV', 'Maldives', 'Asia', 'Southern Asia'),
  ('ML', 'Mali', 'Africa', 'Sub-Saharan Africa'),
  ('MT', 'Malta', 'Europe', 'Southern Europe'),
  ('MH', 'Marshall Islands', 'Oceania', 'Micronesia'),
  ('MR', 'Mauritania', 'Africa', 'Sub-Saharan Africa'),
  ('MU', 'Mauritius', 'Africa', 'Sub-Saharan Africa'),
  ('MX', 'Mexico', 'Americas', 'Central America'),
  ('FM', 'Micronesia', 'Oceania', 'Micronesia'),
  ('MD', 'Moldova', 'Europe', 'Eastern Europe'),
  ('MC', 'Monaco', 'Europe', 'Western Europe'),
  ('MN', 'Mongolia', 'Asia', 'Eastern Asia'),
  ('ME', 'Montenegro', 'Europe', 'Southern Europe'),
  ('MA', 'Morocco', 'Africa', 'Northern Africa'),
  ('MZ', 'Mozambique', 'Africa', 'Sub-Saharan Africa'),
  ('MM', 'Myanmar', 'Asia', 'South-Eastern Asia'),
  ('MM', 'Myanmar (Burma)', 'Asia', 'South-Eastern Asia'),
  ('NA', 'Namibia', 'Africa', 'Sub-Saharan Africa'),
  ('NR', 'Nauru', 'Oceania', 'Micronesia'),
  ('NP', 'Nepal', 'Asia', 'Southern Asia'),
  ('NL', 'Netherlands', 'Europe', 'Western Europe'),
  ('NZ', 'New Zealand', 'Oceania', 'Australia and New Zealand'),
  ('NI', 'Nicaragua', 'Americas', 'Central America'),
  ('NE', 'Niger', 'Africa', 'Sub-Saharan Africa'),
  ('NG', 'Nigeria', 'Africa', 'Sub-Saharan Africa'),
  ('MK', 'North Macedonia', 'Europe', 'Southern Europe'),
  ('NO', 'Norway', 'Europe', 'Northern Europe'),
  ('OM', 'Oman', 'Asia', 'Western Asia'),
  ('PK', 'Pakistan', 'Asia', 'Southern Asia'),
  ('PW', 'Palau', 'Oceania', 'Micronesia'),
  ('PA', 'Panama', 'Americas', 'Central America'),
  ('PG', 'Papua New Guinea', 'Oceania', 'Melanesia'),
  ('PR', 'Puerto Rico', 'Americas', 'South America')
  ('PY', 'Paraguay', 'Americas', 'South America'),
  ('PE', 'Peru', 'Americas', 'South America'),
  ('PH', 'Philippines', 'Asia', 'South-Eastern Asia'),
  ('PL', 'Poland', 'Europe', 'Eastern Europe'),
  ('PT', 'Portugal', 'Europe', 'Southern Europe'),
  ('QA', 'Qatar', 'Asia', 'Western Asia'),
  ('RO', 'Romania', 'Europe', 'Eastern Europe'),
  ('RU', 'Russia', 'Europe', 'Eastern Europe'),
  ('RW', 'Rwanda', 'Africa', 'Sub-Saharan Africa'),
  ('KN', 'Saint Kitts and Nevis', 'Americas', 'Caribbean'),
  ('LC', 'Saint Lucia', 'Americas', 'Caribbean'),
  ('VC', 'Saint Vincent and the Grenadines', 'Americas', 'Caribbean'),
  ('WS', 'Samoa', 'Oceania', 'Polynesia'),
  ('SM', 'San Marino', 'Europe', 'Southern Europe'),
  ('ST', 'Sao Tome and Principe', 'Africa', 'Sub-Saharan Africa'),
  ('SA', 'Saudi Arabia', 'Asia', 'Western Asia'),
  ('SN', 'Senegal', 'Africa', 'Sub-Saharan Africa'),
  ('RS', 'Serbia', 'Europe', 'Southern Europe'),
  ('SC', 'Seychelles', 'Africa', 'Sub-Saharan Africa'),
  ('SL', 'Sierra Leone', 'Africa', 'Sub-Saharan Africa'),
  ('SG', 'Singapore', 'Asia', 'South-Eastern Asia'),
  ('SK', 'Slovakia', 'Europe', 'Eastern Europe'),
  ('SI', 'Slovenia', 'Europe', 'Southern Europe'),
  ('SB', 'Solomon Islands', 'Oceania', 'Melanesia'),
  ('SO', 'Somalia', 'Africa', 'Sub-Saharan Africa'),
  ('ZA', 'South Africa', 'Africa', 'Sub-Saharan Africa'),
  ('ES', 'Spain', 'Europe', 'Southern Europe'),
  ('LK', 'Sri Lanka', 'Asia', 'Southern Asia'),
  ('SD', 'Sudan', 'Africa', 'Northern Africa'),
  ('SR', 'Suriname', 'Americas', 'South America'),
  ('SE', 'Sweden', 'Europe', 'Northern Europe'),
  ('CH', 'Switzerland', 'Europe', 'Western Europe'),
  ('SY', 'Syria', 'Asia', 'Western Asia'),
  ('TW', 'Taiwan', 'Asia', 'Eastern Asia'),
  ('TJ', 'Tajikistan', 'Asia', 'Central Asia'),
  ('TZ', 'Tanzania', 'Africa', 'Sub-Saharan Africa'),
  ('TH', 'Thailand', 'Asia', 'South-Eastern Asia'),
  ('TL', 'Timor-Leste', 'Asia', 'South-Eastern Asia'),
  ('TG', 'Togo', 'Africa', 'Sub-Saharan Africa'),
  ('TO', 'Tonga', 'Oceania', 'Polynesia'),
  ('TT', 'Trinidad and Tobago', 'Americas', 'Caribbean'),
  ('TN', 'Tunisia', 'Africa', 'Northern Africa'),
  ('TR', 'Turkey', 'Asia', 'Western Asia'),
  ('TR', 'Türkiye', 'Asia', 'Western Asia'),
  ('TM', 'Turkmenistan', 'Asia', 'Central Asia'),
  ('TV', 'Tuvalu', 'Oceania', 'Polynesia'),
  ('UG', 'Uganda', 'Africa', 'Sub-Saharan Africa'),
  ('UA', 'Ukraine', 'Europe', 'Eastern Europe'),
  ('AE', 'United Arab Emirates', 'Asia', 'Western Asia'),
  ('GB', 'United Kingdom', 'Europe', 'Northern Europe'),
  ('US', 'United States', 'Americas', 'Northern America'),
  ('UY', 'Uruguay', 'Americas', 'South America'),
  ('UZ', 'Uzbekistan', 'Asia', 'Central Asia'),
  ('VU', 'Vanuatu', 'Oceania', 'Melanesia'),
  ('VE', 'Venezuela', 'Americas', 'South America'),
  ('VN', 'Vietnam', 'Asia', 'South-Eastern Asia'),
  ('YE', 'Yemen', 'Asia', 'Western Asia'),
  ('ZM', 'Zambia', 'Africa', 'Sub-Saharan Africa'),
  ('ZW', 'Zimbabwe', 'Africa', 'Sub-Saharan Africa');
