// stdlib
#include <cassert>
#include <cerrno>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
// system
#include <fcntl.h>
#include <netinet/in.h>
#include <poll.h>
#include <stdio.h>
#include <string.h>
#include <sys/fcntl.h>
#include <sys/poll.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <sys/uio.h>
#include <unistd.h>

// c++
#include <iostream>
#include <map>
#include <string>
#include <vector>

// const size_t k_max_msg = 4096;
const size_t k_max_msg = 32 << 20;

enum {
  RES_OK = 0,
  RES_ERR = 1, // error
  RES_NX = 2,  // key not found
};

struct Response {
  uint32_t status = 0;
  std::vector<uint8_t> data;
};

static void die(const char *msg) {
  int err = errno;
  fprintf(stderr, "[%d] %s\n", err, msg);
  std::abort();
}

static void msg(const char *msg) { fprintf(stderr, "%s\n", msg); }

struct Conn {
  int fd = -1;
  // application intentions
  bool want_read = false;
  bool want_write = false;
  bool want_close = false;

  // buffered input and output
  std::vector<uint8_t> incoming; // data to be parsed by the application
  std::vector<uint8_t> outgoing; // responses generated by the application
};

static void buf_append(std::vector<uint8_t> &buf, const uint8_t *data,
                       size_t len) {
  buf.insert(buf.end(), data, data + len);
}

static void buf_consume(std::vector<uint8_t> &buf, size_t n) {
  buf.erase(buf.begin(), buf.begin() + n);
}

/*
 *TEMP
 */

static std::map<std::string, std::string> g_data;

static void do_request(std::vector<std::string> &cmd, Response &out) {
  if (cmd.size() == 2 && cmd[0] == "get") {
    auto it = g_data.find(cmd[1]);
    if (it == g_data.end()) {
      out.status = RES_NX; // not found
      return;
    }
    const std::string &val = it->second;
    out.data.assign(val.begin(), val.end());
  } else if (cmd.size() == 3 && cmd[0] == "set") {
    g_data[cmd[1]].swap(cmd[2]);
  } else if (cmd.size() == 2 && cmd[0] == "del") {
    g_data.erase(cmd[1]);
  } else {
    out.status = RES_ERR; // unrecognized command
  }
}

static void make_response(const Response &resp, std::vector<uint8_t> &out) {
  uint32_t resp_len = 4 + (uint32_t)resp.data.size();
  buf_append(out, (const uint8_t *)&resp_len, 4);
  buf_append(out, (const uint8_t *)&resp.status, 4);
  buf_append(out, resp.data.data(), resp.data.size());
}

/*
 *END TEMP
 */

static void fd_set_nb(int fd) {
  errno = 0;
  int flags = fcntl(fd, F_GETFL, 0);
  if (errno) {
    die("fcntl() error");
    return;
  }

  flags |= O_NONBLOCK;
  errno = 0;
  (void)fcntl(fd, F_SETFL, flags);
  if (errno) {
    die("fcntl() error");
    return;
  }
}

static Conn *handle_accept(int fd) {
  // accept
  struct sockaddr_in client_addr = {};
  socklen_t addrlen = sizeof(client_addr);
  int connfd = accept(fd, (struct sockaddr *)&client_addr, &addrlen);
  if (connfd < 0) {
    msg("accept() error");
    return NULL;
  }
  uint32_t ip = client_addr.sin_addr.s_addr;
  fprintf(stderr, "new client from %u.%u.%u.%u:%u\n", ip & 255, (ip >> 8) & 255,
          (ip >> 16) & 255, ip >> 24, ntohs(client_addr.sin_port));

  // set the new connection fd to nonblocking mode
  fd_set_nb(connfd);

  // create a `struct Conn`
  Conn *conn = new Conn();
  conn->fd = connfd;
  conn->want_read = true;
  return conn;
}

static void handle_write(Conn *conn) {
  assert(conn->outgoing.size() > 0);
  ssize_t rv = write(conn->fd, &conn->outgoing[0], conn->outgoing.size());
  if (rv < 0 && errno == EAGAIN) {
    return;
  }
  if (rv < 0) {
    msg("write() error");
    conn->want_close = true;
    return;
  }

  // remove written data from `outgoing`
  buf_consume(conn->outgoing, (size_t)rv);

  // update the readiness intention
  if (conn->outgoing.size() == 0) { // all data written
    conn->want_read = true;
    conn->want_write = false;
  } // else: want write
}

static bool read_u32(const uint8_t *cur, const uint8_t *end, uint32_t &out) {
  if (cur + 4 > end) {
    return false;
  }
  memcpy(&out, cur, 4);
  cur += 4;
  return true;
}

static bool read_str(const uint8_t *&cur, const uint8_t *end, size_t n,
                     std::string &out) {
  if (cur + n > end) {
    return false;
  }
  out.assign(cur, cur + n);
  cur += n;
  return true;
}

// add string to out: [ nstr | len | str1 | len2 | str 2 | ... ]
static int32_t parse_request(const uint8_t *data, size_t size,
                             std::vector<std::string> &out) {
  const uint8_t *end = data + size;
  uint32_t nstr = 0;
  if (!read_u32(data, end, nstr)) {
    return -1;
  }
  if (nstr > k_max_msg) {
    return -1; // safety limit
  }

  while (out.size() < nstr) {
    uint32_t len = 0;
    if (!read_u32(data, end, len)) {
      return -1;
    }
    out.push_back(std::string());
    if (!read_str(data, end, len, out.back())) {
      return -1;
    }
  }
  if (data != end) {
    return -1; // trailing garbage
  }

  return 0;
}

static bool try_one_request(Conn *conn) {
  // try to parse the protocol: message header
  if (conn->incoming.size() < 4) {
    return false; // want read
  }
  uint32_t len = 0;
  memcpy(&len, conn->incoming.data(), 4);
  if (len > k_max_msg) {
    msg("too long");
    conn->want_close = true;
    return false; // want close
  }
  // message body
  if (4 + len > conn->incoming.size()) {
    return false; // want read
  }
  const uint8_t *request = &conn->incoming[4];

  // got one request, do some application logic
  printf("client says: len:%d data:%.*s\n", len, len < 100 ? len : 100,
         request);

  // TODO parse the request
  // std::vector<std::string> cmd;
  // if (parse_request(request, len, cmd) < 0) {
  // conn->want_close = true;
  // return false; // error
  //}

  // for (const std::string &c : cmd) {
  // std::cout << c << '\n';
  //}

  // TODO perform the request

  // TODO generate the response

  // generate the response (echo)
  buf_append(conn->outgoing, (const uint8_t *)&len, 4);
  buf_append(conn->outgoing, request, len);
  buf_consume(conn->incoming, 4 + len);
  return true; // success
}

static void handle_read(Conn *conn) {
  // read some data
  uint8_t buf[64 * 1024];
  ssize_t rv = read(conn->fd, buf, sizeof(buf));
  if (rv < 0 && errno == EAGAIN) {
    return; // actually not ready
  }
  // handle IO error
  if (rv < 0) {
    msg("read() error");
    conn->want_close = true;
    return; // want close
  }
  // handle EOF
  if (rv == 0) {
    if (conn->incoming.size() == 0) {
      msg("client closed");
    } else {
      msg("unexpected EOF");
    }
    conn->want_close = true;
    return;
  }
  // got some new data
  buf_append(conn->incoming, buf, (size_t)rv);

  // parse requests and generate responses
  while (try_one_request(conn)) {
  }

  // update the readiness intention
  if (conn->outgoing.size() > 0) { // has a response
    conn->want_read = false;
    conn->want_write = true;
    // The socket is likely ready to write in a request-response protocol,
    // try to write it without waiting for the next iteration.
    return handle_write(conn);
  } // else: want read
}

// static int32_t write_all(int fd, char *buf, size_t n) {
// while (n > 0) {
// size_t rv = write(fd, buf, n);
// if (rv < 0) {
// return -1;
//}
//// assert((size_t)rv <= n);
// n -= (size_t)rv;
// buf += rv;
//}
// return 0;
//}

// static int32_t process_request(int connfd) {
//// verify if message is correct - header is 4 bytes
// char rbuf[4 + k_max_msg];
// errno = 0;
// int err = read_full(connfd, rbuf, 4);
// if (err < 0) {
// msg(errno == 0 ? "EOF" : "read() error");
//}

//// read
// uint32_t len = 0;
// memcpy(&len, rbuf, 4);
// if (len > k_max_msg) {
// msg("client message too long");
// return -1;
//}
// err = read_full(connfd, &rbuf[4], len);
// if (err < 0) {
// msg("read() error");
//}

//// write
// printf("client says %.*s\n", len, &rbuf[4]);

//// respond using protocol
// const char reply[] = "received";
// char wbuf[4 + sizeof(reply)];
// len = (uint32_t)strlen(reply);
// memcpy(wbuf, &len, 4);
// memcpy(&wbuf[4], reply, len);
// return write_all(connfd, wbuf, 4 + len);
//}

int main() {
  // create socket
  int fd = socket(PF_INET, SOCK_STREAM, 0);
  if (fd < 0) {
    die("socket()");
  }
  int val = 1;
  setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

  // bind socket address
  struct sockaddr_in addr = {};
  addr.sin_family = AF_INET;
  addr.sin_port = htons(1234);
  addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
  int rv = bind(fd, (const struct sockaddr *)&addr, sizeof(addr));
  if (rv < 0) {
    die("bind()");
  }

  // set the listen fd in nonblocking mode
  fd_set_nb(fd);

  // listen to endpoint
  rv = listen(fd, SOMAXCONN);
  if (rv < 0) {
    die("listen()");
  }

  // process all client connections
  std::vector<Conn *> fd2conn;
  std::vector<struct pollfd> poll_args;
  while (true) {
    // initialize sockets: listening socket + connection sockets
    // fd2conn.clear();
    poll_args.clear();
    struct pollfd pfd = {fd, POLLIN, 0};
    poll_args.push_back(pfd);

    for (Conn *conn : fd2conn) {
      if (!conn) {
        continue;
      }
      struct pollfd pfd = {conn->fd, POLLERR, 0};
      if (conn->want_read) {
        pfd.events |= POLLIN;
      }
      if (conn->want_write) {
        pfd.events |= POLLOUT;
      }
      poll_args.push_back(pfd);
    }

    // wait for readiness
    int rv = poll(poll_args.data(), (nfds_t)poll_args.size(), -1);
    if (rv < 0 && errno == EINTR) {
      continue; // not an error
    }
    if (rv < 0) {
      die("poll() error");
    }

    // handle listening socket
    if (poll_args[0].revents) {
      if (Conn *conn = handle_accept(fd)) {
        // put it in the map
        if (fd2conn.size() <= (size_t)conn->fd) {
          fd2conn.resize(conn->fd + 1);
        }
        assert(!fd2conn[conn->fd]);
        fd2conn[conn->fd] = conn;
      }
    }

    // TODO handle connections sockets
    // note: start at i=1 for all connections sockets
    for (size_t i = 1; i < poll_args.size(); i++) {
      uint32_t ready = poll_args[i].revents;
      if (ready == 0) {
        continue;
      }

      Conn *conn = fd2conn[poll_args[i].fd];
      if (ready & POLLIN) {
        assert(conn->want_read);
        handle_read(conn);
      }
      if (ready & POLLOUT) {
        assert(conn->want_write);
        handle_write(conn);
      }
      if ((ready & POLLERR) || conn->want_close) {
        (void)close(conn->fd);
        fd2conn[conn->fd] = NULL;
        delete conn;
      }
    }
  }
  return 0;
}
