compile:
	g++ -Wall -Wextra -Og -g server.cpp -o server
	g++ -Wall -Wextra -Og -g client.cpp -o client
	# in terminal 1: ./server
	# in terminal 2: ./client

clean:
	rm -rf client.dSYM/ server.dSYM/
	rm server client
	# rm server.log client.log
