name: "taxis"
version: "1.0"
config-version: 2

profile: "taxis"

vars:
  "dbt_datetime_zone": "America/New_York"

model-paths: ["dbt/models"]
analysis-paths: ["dbt/analyses"]
test-paths: ["dbt/tests"]
seed-paths: ["dbt/seeds"]
macro-paths: ["dbt/macros"]
snapshot-paths: ["dbt/snapshots"]
# docs-paths: [directorypath]
# asset-paths: [directorypath]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  taxis:
    staging:
      +materialized: table
      +schema: staging
    intermediate:
      +materialized: table
    marts:
      +materialized: table
      +schema: trips

seeds:
  taxis:
    +schema: staging
