services:
  pgdatabase:
    image: postgres:13
    container_name: pgdatabase
    environment:
      - .env
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER"]
      interval: 30s
      retries: 2

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - .env
    ports:
      - "8080:80"
    networks:
      - pg-network
    depends_on:
      - pgdatabase

  webserver:
    image: apache/airflow:2.10.5
    container_name: webserver
    restart: always
    depends_on:
      - pgdatabase
    environment:
      - .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8081:8081" # host_port:container_port
    command: >
      bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && airflow webserver --port 8081"
    networks:
      - pg-network
    # healthcheck:
    #   test: ["CMD", "curl", "--fail", "http://localhost:8081/health"]
    #   interval: 30s
    #   timeout: 30s
    #   retries: 3

networks:
  pg-network:

volumes:
  ny_taxi_postgres_data:
