services:
  pgdatabase:
    image: postgres:13
    container_name: pgdatabase
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - pg-network
    depends_on:
      - pgdatabase

  airflow-webserver:
    image: apache/airflow:2.10.5
    container_name: airflow-webserver
    restart: always
    depends_on:
      - pgdatabase
    environment:
      - EXECUTOR=Local
    volumes:
      - "./airflow/dags:/opt/airflow/dags"
      - "./airflow/logs:/opt/airflow/logs"
      - "./airflow/plugins:/opt/airflow/plugins"
    ports:
      - "8081:8081" # host_port:container_port
    command: >
      bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && airflow webserver --port 8081"
    networks:
      - pg-network

networks:
  pg-network:
