version: 2

models:
  - name: dim_taxi_vendor
    description: Dimension Table for Taxi Vendor

  - name: dim_payment_type
    description: Dimension Table for Payment Type

  - name: dim_rate_code
    description: Dimension Table for Rate Code

  - name: dim_taxi_type
    description: Dimension Table for Taxi Type

  - name: dim_date
    # FIXME: generate all datetime with hours of days + ranged query for indexes
    description: Dimension Table for date

  - name: dim_time
    description: Dimension Table for time


  - name: dim_location
    description: Dimension Table for location # TODO

  - name: fct_trips
    # FIXME: use datetime id instead of datetime
    description: Fact Table for Taxi Trips
