#!/env/bin/python

class BachelorURL(object):
    BIOINFORMATIQUE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-bio-informatique/',
    CHIMIE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-chimie/',
    INFORMATIQUE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-informatique/',
    MATHEMATIQUES = 'https://admission.umontreal.ca/programmes/baccalaureat-en-mathematiques/',
    MATHEMATIQUES_ECONOMIE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-mathematiques-et-economie/',
    MATHEMATIQUES_INFORMATIQUE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-mathematiques-et-informatique/',
    MATHEMATIQUES_PHYSIQUE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-mathematiques-et-physique/',
    PHYSIQUE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-physique/',
    PHYSIQUE_INFORMATIQUE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-physique-et-informatique/',
    ANTHROPOLOGIE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-anthropologie/',
    COMMUNICATION_POLITIQUE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-communication-et-politique/',
    DEMOGRAPHIE_STATISTIQUES = 'https://admission.umontreal.ca/programmes/baccalaureat-en-demographie-et-statistique/',
    ECONOMIE_POLITIQUE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-economie-et-politique/',
    GEOGRAPHIE_ENVIRONNEMENTALE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-geographie-environnementale/',
    LINGUISTIQUE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-linguistique/',
    PSYCHOLOGIE_SOCIOLOGIE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-psychologie-et-sociologie/',
    POLITIQUE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-science-politique/',
    POLITIQUE_PHILOSOPHIE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-science-politique-et-philosophie/',
    SCIENCE_ECONOMIQUE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-sciences-economiques/',
    SOCIOLOGIE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-sociologie/',
    ETUDES_ALLEMANDES = 'https://admission.umontreal.ca/programmes/baccalaureat-en-etudes-allemandes/',
    ETUDES_ALLEMANDES_HISTOIRE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-etudes-allemandes-et-histoire/',
    ETUDES_ANGLAISES = 'https://admission.umontreal.ca/programmes/baccalaureat-en-etudes-anglaises/',
    ETUDES_ASIATIQUE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-etudes-asiatiques/',
    ETUDES_CLASSIQUE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-etudes-classiques/',
    ETUDES_CLASSIQUE_ANTHROPOLOGIE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-etudes-classiques-et-anthropologie/',
    ETUDES_HISPANIQUES = 'https://admission.umontreal.ca/programmes/baccalaureat-en-etudes-hispaniques/',
    ETUDES_RELIGIEUSES = 'https://admission.umontreal.ca/programmes/baccalaureat-en-etudes-religieuses/',
    HISTOIRE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-histoire/',
    ART = 'https://admission.umontreal.ca/programmes/baccalaureat-en-histoire-de-lart/',
    HISTOIRE_ETUDES_CLASSIQUES = 'https://admission.umontreal.ca/programmes/baccalaureat-en-histoire-et-etudes-classiques/',
    LITTERATURE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-litterature-comparee/',
    PHILOSOPHIE = 'https://admission.umontreal.ca/programmes/baccalaureat-en-philosophie/',
    PHILOSOPHIE_ETUDES_CLASSIQUES= 'https://admission.umontreal.ca/programmes/baccalaureat-en-philosophie-et-etudes-classiques/',


