# https://www.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf

version: 2

models:
  - name: example
    description: yello taxi trip data
    columns:
      - name: VendorID
        description: A code indicating the TPEP provider that provided the record. 1= Creative Mobile Technologies, LLC; 2= VeriFone Inc
        data_tests:
          - not_null
      - name: tpep_pickup_datetime
        description: The date and time when the meter was engaged.
        data_tests:
          - not_null
      - name: tpep_dropoff_datetime
        description: The date and time when the meter was disengaged.
        data_tests:
          - not_null
      - name: passenger_count
        description: The number of passengers in the vehicle.  This is a driver-entered value
      - name: trip_distance
        description: The elapsed trip distance in miles reported by the taximeter.
        data_tests:
          - not_null
      - name: fare_amount
        description: The time-and-distance fare calculated by the meter
        data_tests:
          - not_null
      - name: total_amount
        description: The total amount charged to passengers. Does not include cash tips.
        data_tests:
          - not_null

  - name: stg_yellow_taxis
    description: Staging model for Yellow Taxi trip records
    columns:
      - name: vendor_id
        description: TPEP provider code '(1=Creative Mobile, 2=Curb, 6=Myle, 7=Helix)'
        data_tests:
          - not_null
          - accepted_values:
              values: [1, 2, 6, 7]
      - name: tpep_pickup_datetime
        description: Timestamp when the meter was engaged
        data_tests:
          - not_null
      - name: tpep_dropoff_datetime
        description: Timestamp when the meter was disengaged
        data_tests:
          - not_null
      - name: passenger_count
        description: Number of passengers in the vehicle
        data_tests:
          - not_null
      - name: trip_distance
        description: Distance traveled in miles, as reported by the taximeter
        data_tests:
          - not_null
          # - greater_than:
          #     value: 0
      - name: rate_code_id
        description: Final rate code at end of trip
        data_tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 99]
      - name: store_and_fwd_flag
        description: Indicates if trip was stored before being sent (Y/N)
        data_tests:
          - accepted_values:
              values: ["Y", "N"]
      - name: pu_location_id
        description: Pickup TLC Taxi Zone ID
        data_tests:
          - not_null
      - name: do_location_id
        description: Dropoff TLC Taxi Zone ID
        data_tests:
          - not_null
      - name: payment_type
        description: Payment method '(0=Flex Fare, 1= Credit, 2= Cash, etc.)'
        data_tests:
          - accepted_values:
              values: [0, 1, 2, 3, 4, 5, 6]
      - name: fare_amount
        description: Meter-calculated fare
        data_tests:
          - not_null
          # - greater_than:
          #     value: 0
      - name: extra
        description: Miscellaneous surcharges
      - name: mta_tax
        description: Mandatory tax triggered by metered rate
      - name: tip_amount
        description: Tip amount (Credit card only, cash tips not included)
      - name: tolls_amount
        description: Total toll charges
      - name: improvement_surcharge
        description: Fixed fee charged per trip since 2015
      - name: total_amount
        description: Total charge (excluding cash tips)
        data_tests:
          - not_null
          # - greater_than:
          #     value: 0
      - name: congestion_surcharge
        description: NYS congestion surcharge for trips
      - name: airport_fee
        description: Flat fee for JFK & LGA pickups
      - name: cbd_congestion_fee
        description: MTA Congestion Relief Zone charge starting Jan 5, 2025
