COUNTRY_CODE_MAP = {
    "United States": "US",
    "United Kingdom": "GB",
    "Ireland": "IE",
    "Germany": "DE",
    "Spain": "ES",
    "Italy": "IT",
    "Brazil": "BR",
    "Mexico": "MX",
    "Chile": "CL",
    "Argentina": "AR",
    "Canada": "CA",
    "Guatemala": "GT",
    "Belgium": "BE",
    "Martinique": "MQ",
    "Singapore": "SG",
    "France": "FR",
    "Australia": "AU",
    "Colombia": "CO",
    "Peru": "PE",
    "Portugal": "PT",
    "Netherlands": "NL",
    "Sweden": "SE",
    "Norway": "NO",
    "Denmark": "DK",
    "Finland": "FI",
    "Switzerland": "CH",
    "Austria": "AT",
    "Poland": "PL",
    "Japan": "JP",
    "South Korea": "KR",
    "India": "IN",
    "New Zealand": "NZ",
    "South Africa": "ZA",
}
